version: '3.8'
services:
  # NestJS Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      # Persist uploads folder on the host machine
      - ./uploads:/app/uploads
    networks:
      - backend-network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/src/main.js
      "

networks:
  backend-network:
    driver: bridge