name: Docker and Server Deploys

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: miniroot48
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            miniroot48/urembo-back:latest

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop urembo-back || true
            docker rm urembo-back || true
            docker rmi -f urembohub/urembo-back:latest || true
            docker pull urembohub/urembo-back:latest
            docker run -d --name urembo-back --restart unless-stopped \
              -e DATABASE_URL=postgresql://urembo:urembohub@172.17.0.1:5432/urembo \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -p 3000:3000 \
              urembohub/urembo-back:latest
